# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from autocorrect import Speller
from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QGraphicsScene, QFileDialog
import os

import pytesseract
from difflib import SequenceMatcher as SQ

import shutil

try:
    from PIL import Image
except ImportError:
    import Image


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Picture_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.Picture_graphicsView.setGeometry(QtCore.QRect(20, 80, 281, 151))
        self.Picture_graphicsView.setObjectName("Picture_graphicsView")
        self.captureBtn = QtWidgets.QPushButton(self.centralwidget)
        self.captureBtn.setGeometry(QtCore.QRect(370, 80, 141, 31))
        self.captureBtn.setObjectName("captureBtn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 571, 31))
        self.frame.setStyleSheet("background-color: blue;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 501, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(370, 200, 141, 31))
        self.resetBtn.setObjectName("resetBtn")
        self.translateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.translateBtn.setGeometry(QtCore.QRect(370, 120, 141, 31))
        self.translateBtn.setObjectName("translateBtn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 71, 16))
        self.label_3.setObjectName("label_3")
        self.translationTxt = QtWidgets.QTextBrowser(self.centralwidget)
        self.translationTxt.setGeometry(QtCore.QRect(100, 250, 441, 31))
        self.translationTxt.setObjectName("translationTxt")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 300, 71, 16))
        self.label_4.setObjectName("label_4")
        self.autoTranslateTxt = QtWidgets.QTextBrowser(self.centralwidget)
        self.autoTranslateTxt.setGeometry(QtCore.QRect(100, 300, 441, 31))
        self.autoTranslateTxt.setObjectName("autoTranslateTxt")
        self.autocorrectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.autocorrectBtn.setGeometry(QtCore.QRect(370, 160, 141, 31))
        self.autocorrectBtn.setObjectName("autocorrectBtn")
        self.browseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.browseBtn.setGeometry(QtCore.QRect(10, 35, 113, 32))
        self.browseBtn.setObjectName("browseBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 40, 411, 21))
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "OCR Handrwiting Detection"))
        self.captureBtn.setText(_translate("MainWindow", "CAPTURE"))
        self.label_2.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;\">OCR Handwriting Detection</span></p></body></html>"))
        self.resetBtn.setText(_translate("MainWindow", "RESET"))
        self.translateBtn.setText(_translate("MainWindow", "TRANSLATE"))
        self.label_3.setText(_translate("MainWindow", "Translation:"))
        self.label_4.setText(_translate("MainWindow", "Autocorrect"))
        self.autocorrectBtn.setText(_translate("MainWindow", "AUTOCORRECT"))
        self.browseBtn.setText(_translate("MainWindow", "BROWSE"))
        self.label.setText(_translate(
            "MainWindow", "/Users/Zeraphim/Desktop/Proto_Test/Images/test3.png"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
